### ISSUE TITLE
Unable to pull versions

### ISSUE THREAD

**Issue by frugecn** [dougbw/pwsh-terrafun#1]
Using Powershell 7.2.3, I can no longer retrieve the version list from releases.terraform.io.  I don't know if it is a change in PS 7.2.3 or a change on the releases site.

PS ❯  tf version list                                                                                                                                                            2022-05-11 15:20:42 
Sort-Object: C:\Program Files\PowerShell\Modules\Terrafun\1.5.0\Private\Get-TerraformVersions.ps1:13
Line |
  13 |      Return [string[]]($Releases | Sort-Object {[version] $_})
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "" to type "System.Version". Error: "Version string portion was too short or too long. (Parameter 'input')"

config.json
`
{
  "DesiredVersion": null,
  "LastUpdateCheck": "2022-05-11T21:11:42",
  "AvailableVersions": [
    ""
  ]
}
`

**Comment by dougbw** [comment]
Hi,

Thanks for raising this, there has been a change on the hashicorp release page which is parsed as html - it looks like they have removed a trailing slash which is breaking the regex matching which was used to filter out alpha/beta/rc releases.

 Ideally this data would come from an API which would make it less prone to failing when changes are made, but I never found an official one (checkpoint only seems to return the latest version), and this is the first time this page has changed in a few years.

The test suite is failing due to this change -  I will push a PR to fix all of this shortly and a new release will be published once ready.

Many thanks,
Doug

**Comment by dougbw** [comment]
It seems that hashicorp have just published an API for this - https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api in the past few days. I will still push the hotfix for the time being but once everything is working will subsequently integrate with the API properly.

**Comment by dougbw** [comment]
PR merged: https://github.com/dougbw/pwsh-terrafun/pull/2
New version published to pwsh gallery: https://www.powershellgallery.com/packages/Terrafun/1.5.3

Update using the following:
```
Uninstall-Module -Name terrafun -AllVersions -Force
Install-Module terrafun -Force
```
